# Nutrients distribution {#distribution}

This section presents the analyses that illustrates the distribution of nutrients within various components of small-scale fisheries in East Timor.

## Fish groups 

```{r echo=FALSE, fig.height=8, fig.width=7, message=FALSE, warning=FALSE, out.width='80%', fig.cap="The bar chart illustrates the contribution of a variety of marine food sources to the Recommended Nutrient Intake (RNI) for six fundamental nutrients, based on a 100g portion. Each bar is a color-segmented stacked visual, with distinct hues corresponding to individual nutrients, and white numbers within indicating the specific percentage contribution of each nutrient. The chart incorporates the mean annual catch in metric tons for each marine species from 2018 to 2023, presented at the end of each bar, providing a view of both the nutritional value and the harvest volume of these essential food sources. The transparency of these values is adjusted to reflect each species' relative contribution to the mean annual catch"}

library(ggplot2)
library(ggforce)

catch_groups_name <-
  timor.nutrients::catch_groups %>%
  dplyr::select(
    grouped_taxa = interagency_code,
    catch_name
  )

tot_catch <-
  timor.nutrients::region_stats %>%
  dplyr::mutate(year = lubridate::year(date_bin_start)) %>%
  dplyr::group_by(grouped_taxa, year) %>%
  dplyr::summarise(catch = sum(catch)) %>%
  dplyr::group_by(grouped_taxa) %>%
  dplyr::summarise(catch = mean(catch)) %>%
  dplyr::left_join(catch_groups_name) %>%
  dplyr::select(-grouped_taxa) %>%
  dplyr::select(catch_name, catch) %>%
  dplyr::mutate(catch = catch / 1000)

base_plot <-
  timor.nutrients::nutrients_table %>%
  dplyr::left_join(catch_groups_name) %>%
  dplyr::select(catch_name, Selenium_mu:Vitamin_A_mu) %>%
  rename_nutrients_mu(hyphen = FALSE) %>%
  tidyr::pivot_longer(-catch_name, names_to = "nutrient", values_to = "concentration") %>%
  dplyr::filter(!nutrient == "selenium" & !catch_name %in% "Other") %>%
  dplyr::left_join(RDI_tab) %>%
  dplyr::mutate(
    nutrient = stringr::str_to_title(nutrient),
    nutrient = dplyr::case_when(
      nutrient == "Omega3" ~ "Omega-3",
      nutrient == "Vitamina" ~ "Vitamin-A",
      TRUE ~ nutrient
    )
  ) %>%
  dplyr::mutate(rdi = (concentration * 100) / conv_factor) %>%
  dplyr::group_by(catch_name) %>%
  dplyr::mutate(tot = sum(rdi, na.rm = T)) %>%
  dplyr::arrange(-tot) %>%
  dplyr::left_join(tot_catch) %>%
  tidyr::replace_na(list(catch = 0)) %>%
  dplyr::arrange(dplyr::desc(nutrient))

tot_catch_plot <-
  base_plot %>%
  dplyr::group_by(catch_name) %>% # Added .drop false to ensure that all factor levels remain in plot
  dplyr::summarise(
    catch = dplyr::first(catch),
    tot = dplyr::first(tot)
  )

ggplot2::ggplot() +
  ggplot2::theme_bw() +
  ggchicklet::geom_chicklet(base_plot,
    mapping = ggplot2::aes(
      y = rdi, x = reorder(catch_name, tot),
      fill = nutrient,
      color = nutrient
    ),
    position = ggplot2::position_stack(reverse = FALSE),
    alpha = 0.8,
    width = 1
  ) +
  geom_text(base_plot,
    mapping = aes(y = rdi, x = reorder(catch_name, tot), label = round(rdi, 2) * 100),
    position = position_stack(0.5),
    color = "white",
    size = 3
  ) +
  geom_text(tot_catch_plot,
    mapping = aes(
      y = tot, x = reorder(catch_name, tot),
      label = scales::comma(round(catch, 0), suffix = " t"),
      alpha = sqrt(catch)
    ),
    size = 4,
    nudge_y = 0.1
  ) +
  ggplot2::scale_fill_manual(values = timor.nutrients::palettes$nutrients_palette) +
  ggplot2::scale_color_manual(values = timor.nutrients::palettes$nutrients_palette) +
  ggplot2::scale_y_continuous(labels = scales::percent, n.breaks = 10) +
  ggplot2::labs(x = "", y = "Matched RNI from 100g portion", fill = "Nutrient") +
  ggplot2::theme(
    legend.position = "bottom",
    panel.grid = element_blank()
  ) +
  coord_flip(expand = FALSE, ylim = c(0, 1.55)) +
  guides(
    alpha = "none",
    color = "none"
  )
```



## Habitat and gear type

```{r echo=FALSE, fig.height=7, fig.width=7, message=FALSE, warning=FALSE, fig.cap="Sankey diagram showing the relative distribution of key nutrients across various marine habitats and the corresponding extraction by different fishing gear types used in Timor-Est small-scale fisheries."}
parallel_plot <-
  timor.nutrients::kobo_trips %>%
  dplyr::mutate(habitat = ifelse(habitat == "Deep", "Pelagic", habitat)) %>% 
  dplyr::select(habitat, gear_type, Selenium_mu:Vitamin_A_mu) %>%
  rename_nutrients_mu() %>%
  tidyr::pivot_longer(-c(habitat, gear_type), names_to = "nutrient", values_to = "concentration_g") %>%
  dplyr::group_by(habitat, gear_type, nutrient) %>%
  dplyr::summarise(concentration_g = sum(concentration_g, na.rm = T)) %>%
  # get relative values
  dplyr::group_by(nutrient) %>%
  dplyr::mutate(
    nutrient_sum = sum(concentration_g),
    concentration_g = concentration_g / nutrient_sum * 100
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(dplyr::across(habitat:nutrient, ~ as.factor(.x))) %>%
  dplyr::mutate(
    nutrient = as.factor(nutrient)
  ) %>%
  dplyr::mutate(
    nutrient = stringr::str_to_title(nutrient),
    nutrient = dplyr::case_when(
      nutrient == "Omega3" ~ "Omega-3",
      nutrient == "Vitamina" ~ "Vitamin-A",
      TRUE ~ nutrient
    )
  ) %>%
  dplyr::rename(
    "Nutrient" = nutrient,
    "Habitat" = habitat,
    "Gear type" = gear_type
  ) %>%
  ggforce::gather_set_data(c(3, 1, 2))

parallel_plot$x <- factor(parallel_plot$x,
                          levels = c("3", "1", "2"),
                          labels = c("Nutrient", "Habitat", "Gear type")
)

parallel_plot$y <- factor(parallel_plot$y, levels = c(
  "Protein", "Omega-3", "Calcium", "Iron", "Vitamin-A", "Zinc", "Selenium",
  "Reef", "Pelagic", "FAD", "Beach", "Traditional FAD", "Mangrove", "Seagrass",
  "gill net", "seine net", "spear gun", "hand line", "long line", "manual collection",
  "beach seine", "trap", "cast net"
))

parallel_plot %>%
  dplyr::filter(!Nutrient == "Selenium") %>%
  na.omit() %>%
  ggplot(aes(x, id = id, split = y, value = concentration_g)) +
  ggforce::geom_parallel_sets(aes(fill = Nutrient), alpha = 0.7, axis.width = 0.1) +
  ggforce::geom_parallel_sets_axes(axis.width = 0.25, fill = "grey95") +
  ggforce::geom_parallel_sets_labels(colour = "grey30", angle = 0, size = 3.5) +
  scale_x_discrete(name = NULL, expand = c(0, 0.2)) +
  scale_y_continuous(breaks = NULL, expand = c(0.05, 0)) +
  theme_minimal(12) +
  scale_fill_manual(values = timor.nutrients::palettes$nutrients_palette) +
  # scale_fill_manual(values = c("#508AA8", "grey95", "#BD9391")) +
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "bottom",
    panel.grid.major = element_blank(),
    axis.text = element_text(size = 12, color = "black")
  ) +
  labs(fill = "")

```

## Nutritional contribution and economic profiling

```{r echo=FALSE, fig.height=5, fig.width=9, message=FALSE, warning=FALSE, fig.cap="Nutritional and economic profiling of key fish groups within the Timor-Leste fishery.Panel A, Distribution of nutritional content among different functional fish groups: Small pelagics, Large pelagics, Small demersals, Large demersals, Sharks and rays and Other groups, that includes shrimps, molluscs, cephalopods and crustaceans. The plot shows the ranked contribution of each functional fish to the supply of calcium, omega-3, iron, protein, vitamin A, and zinc during the period 2018-2023. Panel B, Comparative analysis of nutritional score versus economic accessibility for key fish groups. This scatter plot displays the relationship between the cumulative nutritional score and the market price for various fish groups within Timor-Leste fishery. The x-axis quantifies the cumulative contribution to the Recommended Nutrient Intake (RNI) for six essential nutrients (zinc, protein, omega-3, calcium, iron, vitamin A) from a 100g portion of each fish group. The y-axis represents the average market price per kilogram for each group. Dot size and the accompanying numerical labels reflect the relative catch percentage of each group, serving as an index of accessibility and availability. Panel C, The bar chart illustrates the contribution of each habitat to the Recommended Nutrient Intake (RNI) for six fundamental nutrients, based on a 100g portion. Each bar is a color-segmented stacked visual, with distinct hues corresponding to individual nutrients, and white numbers within indicating the specific percentage contribution of each nutrient."}

groups_plot <- 
  timor.nutrients::region_stats %>%
  dplyr::mutate(fish_group = dplyr::case_when(
    grouped_taxa %in% c("COZ") ~ "Molluscs",
    grouped_taxa %in% c("PEZ") ~ "Shrimps",
    grouped_taxa %in% c("MZZ") ~ "Other",
    grouped_taxa %in% c("SLV", "CRA") ~ "Crustaceans",
    grouped_taxa %in% c("OCZ", "IAX") ~ "Cephalopods",
    grouped_taxa %in% c("SKH", "SRX") ~ "Sharks and rays",
    grouped_taxa %in% c("SNA", "GPX", "PWT", "GRX", "MUI", "BGX") ~ "Large demersals",
    grouped_taxa %in% c("CGX", "TUN", "BEN", "LWX", "BAR", "SFA", "CBA", "DOX", "ECN", "DOS") ~ "Large pelagics",
    grouped_taxa %in% c("YDX", "SPI", "EMP", "SUR", "TRI", "MOJ", "WRA", "MOO", "BWH", "LGE", "MOB", "MHL", "GOX", "THO", "IHX", "APO", "IHX", "PUX", "DRZ", "DSF") ~ "Small demersals",
    grouped_taxa %in% c("RAX", "SDX", "CJX", "CLP", "GZP", "FLY", "KYX", "CLP", "MUL", "MIL", "THF") ~ "Small pelagics",
    TRUE ~ NA_character_
  )) %>%
  dplyr::select(-grouped_taxa) %>% 
  dplyr::group_by(fish_group) %>%
  dplyr::summarise(dplyr::across(dplyr::where(is.numeric), ~ sum(.x, na.rm = T))) %>%
  na.omit() %>% 
  tidyr::pivot_longer(-c(fish_group, catch), names_to = "nutrient") %>%
  dplyr::group_by(nutrient, fish_group) %>%
  dplyr::summarise(value = sum(value)) %>%
  dplyr::arrange(-value, .by_group = TRUE) %>%
  dplyr::select(fish_group, nutrient, value) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    nutrient = as.factor(nutrient),
    fish_group = ifelse(fish_group %in% c("Shrimps", "Molluscs", "Cephalopods", "Crustaceans"), "Other groups", fish_group),
    fish_group = factor(fish_group, levels = c("Shrimps", "Molluscs", "Cephalopods", "Crustaceans",
                                               "Other groups", "Sharks and rays", "Large demersals",
                                               "Small demersals","Large pelagics", "Small pelagics"))
  ) %>%
  dplyr::filter(!nutrient == "selenium") %>%
  dplyr::mutate(
    nutrient = stringr::str_to_title(nutrient),
    nutrient = dplyr::case_when(
      nutrient == "Omega3" ~ "Omega-3",
      nutrient == "Vitamina" ~ "Vitamin-A",
      TRUE ~ nutrient
    )
  ) %>% 
  ggplot(aes(value / 1000, fish_group, fill = nutrient)) +
  theme_bw() +
  geom_col(alpha = 0.85) +
  facet_grid(. ~ nutrient, scales = "free") +
  labs(x = "Tons", y = "") +
  theme(legend.position = "",
        panel.grid = element_blank(),
        strip.background = ggplot2::element_blank(), # This removes the background from the facet titles
        strip.text.x = ggplot2::element_text(face = "bold")
  ) +
  ggplot2::coord_cartesian(expand = T) +
  scale_fill_manual(values = timor.nutrients::palettes$nutrients_palette)+
  scale_x_continuous(n.breaks = 3)

###

revenue_dat <-
  timor.nutrients::catch_data %>%
  tidyr::unnest(landing_catch) %>%
  tidyr::unnest(length_frequency) %>%
  dplyr::filter(!is.na(.data$weight), !is.na(landing_value)) %>%
  dplyr::group_by(landing_id) %>%
  dplyr::mutate(n = dplyr::n()) %>%
  dplyr::filter(n == 1) %>%
  dplyr::select(-n) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(tot_obs = length(unique(landing_id))) %>%
  dplyr::group_by(catch_taxon) %>%
  dplyr::mutate(catch_percent = dplyr::n() / tot_obs * 100) %>%
  dplyr::filter(catch_taxon %in% c("CLP", "GZP", "TUN", "SDX", "FLY", "CGX")) %>%
  dplyr::group_by(.data$landing_id, .data$catch_taxon) %>%
  dplyr::summarise(
    landing_value = dplyr::first(landing_value),
    catch_percent = dplyr::first(catch_percent),
    dplyr::across(
      c(.data$weight:.data$Vitamin_A_mu),
      ~ sum(.x)
    )
  )


models <-
  revenue_dat %>%
  dplyr::ungroup() %>%
  dplyr::select(catch_taxon, landing_value, weight) %>%
  split(.$catch_taxon) %>%
  purrr::map(~ lm(log(landing_value) ~ log(weight), data = .x)) %>%
  purrr::map(~ predict(.x, data.frame(weight = log(100)))) %>%
  dplyr::bind_rows(.id = "catch_taxon") %>%
  dplyr::rename(price = `1`) %>%
  dplyr::mutate(price = round(exp(price) * 10, 2))

revenue_dat <-
  revenue_dat %>%
  rename_nutrients_mu() %>%
  tidyr::pivot_longer(-c(landing_id:weight), names_to = "nutrient") %>%
  dplyr::filter(!nutrient == "selenium") %>%
  dplyr::left_join(RDI_tab) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    value = value / weight * 100,
    inds = value / conv_factor * 100
  ) %>%
  dplyr::group_by(landing_id, catch_taxon) %>%
  dplyr::mutate(inds_100 = sum(inds)) %>%
  dplyr::group_by(catch_taxon) %>%
  dplyr::summarise(
    catch_percent = dplyr::first(catch_percent),
    inds = dplyr::first(inds_100)
  ) %>%
  dplyr::left_join(models) %>%
  dplyr::rename(interagency_code = catch_taxon) %>%
  dplyr::left_join(timor.nutrients::catch_groups, by = "interagency_code") %>%
  dplyr::select(catch_name, catch_percent, price, inds)

revenue_plot <- 
  revenue_dat %>%
  ggplot(aes(inds, price, size = catch_percent, color = catch_name)) +
  theme_bw() +
  geom_point(stroke = 2) +
  geom_text(aes(label = round(catch_percent, 1)), color = "grey30", size = 3.5, vjust = -1.2) +
  scale_size(range = c(3, 8)) +
  coord_cartesian(xlim = c(75, 130), ylim = c(0, 6.4)) +
  scale_x_continuous(labels = scales::label_percent(scale = 1)) +
  scale_y_continuous(labels = scales::label_dollar()) +
  scale_color_viridis_d(alpha = 0.7) +
  theme(panel.grid= element_blank(),
        legend.position = "bottom"
        )+
  guides(size = "none",
         colour = guide_legend(override.aes = list(size=5)
                               )
         ) +
  labs(
    x = "Cumulative nutrient score",
    y = "Price (USD / kg)",
    color = ""
  )
###

habitat_nutrients <-
  timor.nutrients::kobo_trips %>%
  dplyr::select(habitat, weight:Vitamin_A_mu) %>%
  rename_nutrients_mu() %>%
  tidyr::pivot_longer(-c(habitat, weight), names_to = "nutrient") %>%
  dplyr::left_join(RDI_tab) %>%
  dplyr::mutate(
    value = value / weight,
    inds_kg = (value * 1000) / conv_factor
  ) %>%
  dplyr::group_by(habitat, nutrient) %>%
  dplyr::summarise(inds_kg = median(inds_kg, na.rm = T) / 10) %>%
  dplyr::mutate(inds_kg = inds_kg * 100) %>%
  dplyr::filter(!nutrient == "selenium") %>%
  dplyr::mutate(
    nutrient = stringr::str_to_title(nutrient),
    nutrient = dplyr::case_when(
      nutrient == "Omega3" ~ "Omega-3",
      nutrient == "Vitamina" ~ "Vitamin-A",
      TRUE ~ nutrient
    )
  )

habitat_plot <-
ggplot2::ggplot() +
  ggplot2::theme_bw() +
  ggchicklet::geom_chicklet(habitat_nutrients,
                            mapping = ggplot2::aes(
                              y = inds_kg,
                              x = reorder(habitat, inds_kg),
                              fill = nutrient,
                              color = nutrient
                            ),
                            position = ggplot2::position_stack(reverse = FALSE),
                            alpha = 0.8,
                            width = 0.8,
                            radius = grid::unit(3, "pt")
  ) +
  ggplot2::geom_text(habitat_nutrients,
                     mapping = ggplot2::aes(
                       y = inds_kg,
                       x = reorder(habitat, inds_kg),
                       label = round(inds_kg, 0),
                       group = nutrient
                     ),
                     position = ggplot2::position_stack(0.5, reverse = FALSE),
                     color = "white",
                     size = 2.5
  ) +
  ggplot2::scale_fill_manual(values = timor.nutrients::palettes$nutrients_palette) +
  ggplot2::scale_color_manual(values = timor.nutrients::palettes$nutrients_palette) +
  ggplot2::scale_y_continuous(labels = scales::label_percent(scale = 1)) +
  ggplot2::coord_flip(expand = FALSE) +
  ggplot2::theme(legend.position = "bottom",
                 panel.grid = ggplot2::element_blank()) +
  ggplot2::labs(x = "Habitat", fill = "", y = "Matched RNI from 100g portion")+
  ggplot2::guides(
    alpha = "none",
    color = "none",
    fill = guide_legend(override.aes = list(size=7)
    )
  )


second_row_plot <- cowplot::plot_grid(
  revenue_plot + theme(plot.margin = unit(c(0, 0, 0, +2.2), "cm")),
  habitat_plot,
  ncol = 2, 
  align = "h",
  labels = c("B", "C")
)

cowplot::plot_grid(
  groups_plot, 
  second_row_plot, 
  ncol = 1,
  align = "hv", 
  rel_heights = c(0.6, 1),
  labels = "AUTO"
)

```
